version: '2'
services:
    simpleapp-app:
        image: simpleapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://simpleapp-mysql:3306/simpleapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simpleapp-mysql:
        extends:
            file: mysql.yml
            service: simpleapp-mysql
